language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - CI_SERVER=true

install:
  - pip install pip --upgrade
  - pip install -e .
  - pip install -e '.[tests]'

script:
  - ./test.sh
