#!/usr/bin/env python3

from pathlib import Path
import runpy

runpy.run_path(str(Path(__file__).parent / "bootstrap_venvstarter.py"))

manager = __import__("venvstarter").manager("noy_pylama")
manager.add_pypi_deps("pylama==8.4.1", "noseOfYeti==2.3.1")
manager.run()
